version: "3.9"

services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    container_name: zincsearch
    volumes:
      - zincsearch-volume:/data
    ports:
      - "4080:4080"
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=admin123
  go-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: go-api
    volumes:
      - go-api-volume:/app
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - ZINCSEARCH_URI=localhost:4080
      - ZINC_FIRST_USER=admin
      - ZINC_FIRST_PASSWORD=admin123
      - DATA_FILES_PATH="/Users/ysaaac/Downloads/enron_mail_20110402/maildir/"
  vue-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: vue-client
    volumes:
      - vue-client-volume:/app/src
    ports:
      - "9090:80"
    environment:
      - API_URL=localhost:8080

  # Service for backup the indexed db
  backup:
    image: ubuntu
    command: [ "bash", "-c", "tar czvf /backup/zincsearch-backup.tar.gz -C /source ." ]
    volumes:
      - zincsearch-volume:/source
      - ./backup:/backup

  # Service for restore the indexed db
  restore:
    image: ubuntu
    command: [ "bash", "-c", "rm -rf /target/* && tar xzvf /backup/zincsearch-backup.tar.gz -C /target" ]
    volumes:
      - zincsearch-volume:/target
      - ./backup:/backup

volumes:
  zincsearch-volume:
  go-api-volume:
  vue-client-volume:
